
import os
_this_dir = os.path.dirname(os.path.abspath(__file__))
sources = [

#https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160
["__cplusplus","std,microsoft"],
["__DATE__","std,microsoft"],
["__FILE__","std,microsoft"],
["__FILE__","std,microsoft"],
["__STDC__","std,microsoft"],
["__STDC_HOSTED__","std,microsoft"],
["__STDC_NO_ATOMICS__","std,microsoft"],
["__STDC_NO_COMPLEX__","std,microsoft"],
["__STDC_NO_THREADS__","std,microsoft"],
["__STDC_NO_VLA__","std,microsoft"],
["__STDC_VERSION__","std,microsoft"],
["__STDCPP_THREADS__","std,microsoft"],
["__TIME__","std,microsoft"],

#https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160
["__ATOM__", "msvc,microsoft"],
["__AVX__", "msvc,microsoft"],
["__AVX2__", "msvc,microsoft"],
["__AVX512BW__", "msvc,microsoft"],
["__AVX512CD__", "msvc,microsoft"],
["__AVX512DQ__", "msvc,microsoft"],
["__AVX512F__", "msvc,microsoft"],
["__AVX512VL__", "msvc,microsoft"],
["__CLR_VER", "msvc,microsoft"],
["__CLR_VER", "msvc,microsoft"],
["_CONTROL_FLOW_GUARD", "msvc,microsoft"],
["__COUNTER__", "msvc,microsoft"],
["__cplusplus_cli", "msvc,microsoft"],
["__cplusplus_winrt", "msvc,microsoft"],
["_CPPRTTI", "msvc,microsoft"],
["_CPPUNWIND", "msvc,microsoft"],
["_DEBUG", "msvc,microsoft"],
["_DLL", "msvc,microsoft"],
["__FUNCDNAME__", "msvc,microsoft"],
["__FUNCSIG__", "msvc,microsoft"],
["__FUNCTION__", "msvc,microsoft"],
["_INTEGRAL_MAX_BITS", "msvc,microsoft"],
["__INTELLISENSE__", "msvc,microsoft"],
["_ISO_VOLATILE", "msvc,microsoft"],
["_KERNEL_MODE", "msvc,microsoft"],
["_M_AMD64", "msvc,microsoft"],
["_M_ARM", "msvc,microsoft"],
["_M_ARM_ARMV7VE", "msvc,microsoft"],
["_M_ARM_FP", "msvc,microsoft"],
["_M_ARM64", "msvc,microsoft"],
["_M_CEE", "msvc,microsoft"],
["_M_CEE_PURE", "msvc,microsoft"],
["_M_CEE_SAFE", "msvc,microsoft"],
["_M_FP_EXCEPT", "msvc,microsoft"],
["_M_FP_FAST", "msvc,microsoft"],
["_M_FP_PRECISE", "msvc,microsoft"],
["_M_FP_STRICT", "msvc,microsoft"],
["_M_IX86", "msvc,microsoft"],
["_M_IX86_FP", "msvc,microsoft"],
["_M_X64", "msvc,microsoft"],
["_MANAGED", "msvc,microsoft"],
["_MSC_BUILD", "msvc,microsoft"],
["_MSC_EXTENSIONS", "msvc,microsoft"],
["_MSC_FULL_VER", "msvc,microsoft"],
["_MSC_VER", "msvc,microsoft"],
["_MSVC_LANG", "msvc,microsoft"],
["__MSVC_RUNTIME_CHECKS", "msvc,microsoft"],
["_MSVC_TRADITIONAL", "msvc,microsoft"],
["_MT", "msvc,microsoft"],
["_NATIVE_WCHAR_T_DEFINED", "msvc,microsoft"],
["_OPENMP", "msvc,microsoft"],
["_PREFAST_", "msvc,microsoft"],
["__TIMESTAMP__", "msvc,microsoft"],
["_VC_NODEFAULTLIB", "msvc,microsoft"],
["_WCHAR_T_DEFINED", "msvc,microsoft"],
["_WIN32", "msvc,microsoft"],
["_WIN64", "msvc,microsoft"],
["_WINRT_DLL", "msvc,microsoft"],
["_ATL_VER", "msvc,microsoft"],
["_MFC_VER", "msvc,microsoft"],

#https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html
["__COUNTER__","gnuc"],
["__GFORTRAN__","gnuc"],
["__GNUC__","gnuc"],
["__GNUC_MINOR__","gnuc"],
["__GNUC_PATCHLEVEL__","gnuc"],
["__GNUG__","gnuc"],
["__STRICT_ANSI__","gnuc"],
["__BASE_FILE__","gnuc"],
["__INCLUDE_LEVEL__","gnuc"],
["__ELF__","gnuc"],
["__VERSION__","gnuc"],
["__OPTIMIZE__","gnuc"],
["__OPTIMIZE_SIZE__","gnuc"],
["__NO_INLINE__","gnuc"],
["__GNUC_GNU_INLINE__","gnuc"],
["__GNUC_STDC_INLINE__","gnuc"],
["__CHAR_UNSIGNED__","gnuc"],
["__WCHAR_UNSIGNED__","gnuc"],
["__REGISTER_PREFIX__","gnuc"],
["__USER_LABEL_PREFIX__","gnuc"],
["__SIZE_TYPE__","gnuc,typedef"],
["__PTRDIFF_TYPE__","gnuc,typedef"],
["__WCHAR_TYPE__","gnuc,typedef"],
["__WINT_TYPE__","gnuc,typedef"],
["__INTMAX_TYPE__","gnuc,typedef"],
["__UINTMAX_TYPE__","gnuc,typedef"],
["__SIG_ATOMIC_TYPE__","gnuc,typedef"],
["__INT8_TYPE__","gnuc,typedef"],
["__INT16_TYPE__","gnuc,typedef"],
["__INT32_TYPE__","gnuc,typedef"],
["__INT64_TYPE__","gnuc,typedef"],
["__UINT8_TYPE__","gnuc,typedef"],
["__UINT16_TYPE__","gnuc,typedef"],
["__UINT32_TYPE__","gnuc,typedef"],
["__UINT64_TYPE__","gnuc,typedef"],
["__INT_LEAST8_TYPE__","gnuc,typedef"],
["__INT_LEAST16_TYPE__","gnuc,typedef"],
["__INT_LEAST32_TYPE__","gnuc,typedef"],
["__INT_LEAST64_TYPE__","gnuc,typedef"],
["__UINT_LEAST8_TYPE__","gnuc,typedef"],
["__UINT_LEAST16_TYPE__","gnuc,typedef"],
["__UINT_LEAST32_TYPE__","gnuc,typedef"],
["__UINT_LEAST64_TYPE__","gnuc,typedef"],
["__INT_FAST8_TYPE__","gnuc,typedef"],
["__INT_FAST16_TYPE__","gnuc,typedef"],
["__INT_FAST32_TYPE__","gnuc,typedef"],
["__INT_FAST64_TYPE__","gnuc,typedef"],
["__UINT_FAST8_TYPE__","gnuc,typedef"],
["__UINT_FAST16_TYPE__","gnuc,typedef"],
["__UINT_FAST32_TYPE__","gnuc,typedef"],
["__UINT_FAST64_TYPE__","gnuc,typedef"],
["__INTPTR_TYPE__","gnuc,typedef"],
["__UINTPTR_TYPE__","gnuc,typedef"],
["__CHAR_BIT__","gnuc"],
["__SCHAR_MAX__","gnuc"],
["__WCHAR_MAX__","gnuc"],
["__SHRT_MAX__","gnuc"],
["__INT_MAX__","gnuc"],
["__LONG_MAX__","gnuc"],
["__LONG_LONG_MAX__","gnuc"],
["__WINT_MAX__","gnuc"],
["__SIZE_MAX__","gnuc"],
["__PTRDIFF_MAX__","gnuc"],
["__INTMAX_MAX__","gnuc"],
["__UINTMAX_MAX__","gnuc"],
["__SIG_ATOMIC_MAX__","gnuc"],
["__INT8_MAX__","gnuc"],
["__INT16_MAX__","gnuc"],
["__INT32_MAX__","gnuc"],
["__INT64_MAX__","gnuc"],
["__UINT8_MAX__","gnuc"],
["__UINT16_MAX__","gnuc"],
["__UINT32_MAX__","gnuc"],
["__UINT64_MAX__","gnuc"],
["__INT_LEAST8_MAX__","gnuc"],
["__INT_LEAST16_MAX__","gnuc"],
["__INT_LEAST32_MAX__","gnuc"],
["__INT_LEAST64_MAX__","gnuc"],
["__UINT_LEAST8_MAX__","gnuc"],
["__UINT_LEAST16_MAX__","gnuc"],
["__UINT_LEAST32_MAX__","gnuc"],
["__UINT_LEAST64_MAX__","gnuc"],
["__INT_FAST8_MAX__","gnuc"],
["__INT_FAST16_MAX__","gnuc"],
["__INT_FAST32_MAX__","gnuc"],
["__INT_FAST64_MAX__","gnuc"],
["__UINT_FAST8_MAX__","gnuc"],
["__UINT_FAST16_MAX__","gnuc"],
["__UINT_FAST32_MAX__","gnuc"],
["__UINT_FAST64_MAX__","gnuc"],
["__INTPTR_MAX__","gnuc"],
["__UINTPTR_MAX__","gnuc"],
["__WCHAR_MIN__","gnuc"],
["__WINT_MIN__","gnuc"],
["__SIG_ATOMIC_MIN__","gnuc"],
["__INT8_C","gnuc,novalue"],
["__INT16_C","gnuc,novalue"],
["__INT32_C","gnuc,novalue"],
["__INT64_C","gnuc,novalue"],
["__UINT8_C","gnuc,novalue"],
["__UINT16_C","gnuc,novalue"],
["__UINT32_C","gnuc,novalue"],
["__UINT64_C","gnuc,novalue"],
["__INTMAX_C","gnuc,novalue"],
["__UINTMAX_C","gnuc,novalue"],
["__SCHAR_WIDTH__","gnuc"],
["__SHRT_WIDTH__","gnuc"],
["__INT_WIDTH__","gnuc"],
["__LONG_WIDTH__","gnuc"],
["__LONG_LONG_WIDTH__","gnuc"],
["__PTRDIFF_WIDTH__","gnuc"],
["__SIG_ATOMIC_WIDTH__","gnuc"],
["__SIZE_WIDTH__","gnuc"],
["__WCHAR_WIDTH__","gnuc"],
["__WINT_WIDTH__","gnuc"],
["__INT_LEAST8_WIDTH__","gnuc"],
["__INT_LEAST16_WIDTH__","gnuc"],
["__INT_LEAST32_WIDTH__","gnuc"],
["__INT_LEAST64_WIDTH__","gnuc"],
["__INT_FAST8_WIDTH__","gnuc"],
["__INT_FAST16_WIDTH__","gnuc"],
["__INT_FAST32_WIDTH__","gnuc"],
["__INT_FAST64_WIDTH__","gnuc"],
["__INTPTR_WIDTH__","gnuc"],
["__INTMAX_WIDTH__","gnuc"],
["__SIZEOF_INT__","gnuc"],
["__SIZEOF_LONG__","gnuc"],
["__SIZEOF_LONG_LONG__","gnuc"],
["__SIZEOF_SHORT__","gnuc"],
["__SIZEOF_POINTER__","gnuc"],
["__SIZEOF_FLOAT__","gnuc"],
["__SIZEOF_DOUBLE__","gnuc"],
["__SIZEOF_LONG_DOUBLE__","gnuc"],
["__SIZEOF_SIZE_T__","gnuc"],
["__SIZEOF_WCHAR_T__","gnuc"],
["__SIZEOF_WINT_T__","gnuc"],
["__SIZEOF_PTRDIFF_T__","gnuc"],
["__BYTE_ORDER__","gnuc"],
["__ORDER_LITTLE_ENDIAN__","gnuc"],
["__ORDER_BIG_ENDIAN__","gnuc"],
["__ORDER_PDP_ENDIAN__","gnuc"],
["__FLOAT_WORD_ORDER__","gnuc"],
["__FLOAT_WORD_ORDER__","gnuc"],
["__DEPRECATED","gnuc"],
["__EXCEPTIONS","gnuc"],
["__GXX_RTTI","gnuc"],
["__USING_SJLJ_EXCEPTIONS__","gnuc"],
["__GXX_EXPERIMENTAL_CXX0X__","gnuc"],
["__GXX_WEAK__","gnuc"],
["__NEXT_RUNTIME__","gnuc"],
["__LP64__","gnuc"],
["_LP64","gnuc"],
["__SSP__","gnuc"],
["__SSP_ALL__","gnuc"],
["__SSP_STRONG__","gnuc"],
["__SSP_EXPLICIT__","gnuc"],
["__SANITIZE_ADDRESS__","gnuc"],
["__SANITIZE_THREAD__","gnuc"],
["__TIMESTAMP__","gnuc"],
["__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1","gnuc"],
["__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2","gnuc"],
["__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4","gnuc"],
["__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8","gnuc"],
["__GCC_HAVE_SYNC_COMPARE_AND_SWAP_16","gnuc"],
["__HAVE_SPECULATION_SAFE_VALUE","gnuc"],
["__GCC_HAVE_DWARF2_CFI_ASM","gnuc"],
["__FP_FAST_FMA","gnuc"],
["__FP_FAST_FMAF","gnuc"],
["__FP_FAST_FMAL","gnuc"],
["__FP_FAST_FMAF16","gnuc"],
["__FP_FAST_FMAF32","gnuc"],
["__FP_FAST_FMAF64","gnuc"],
["__FP_FAST_FMAF128","gnuc"],
["__FP_FAST_FMAF32X","gnuc"],
["__FP_FAST_FMAF64X","gnuc"],
["__FP_FAST_FMAF128X","gnuc"],
["__GCC_IEC_559","gnuc"],
["__GCC_IEC_559_COMPLEX","gnuc"],
["__NO_MATH_ERRNO__","gnuc"],

#https://sourceforge.net/p/predef/wiki/Compilers/
["__ACK__","all,compilers"],
["__apple_build_version__","all,compilers"],
["__ARMCC_VERSION","all,compilers"],
["__AZTEC_C__","all,compilers"],
["__BORLANDC__","all,compilers"],
["__BUILD__","all,compilers"],
["__C166__","all,compilers"],
["__C51__","all,compilers"],
["__CA__","all,compilers"],
["__CC65__","all,compilers"],
["__CC_ARM","all,compilers"],
["__CC_NORCROFT","all,compilers"],
["__CHC__","all,compilers"],
["__clang__","all,compilers"],
["__clang_major__","all,compilers"],
["__clang_minor__","all,compilers"],
["__clang_patchlevel__","all,compilers"],
["__clang_version__","all,compilers"],
["__CMB__","all,compilers"],
["__CODEGEARC__","all,compilers"],
["__COMO__","all,compilers"],
["__COMO_VERSION__","all,compilers"],
["__COMPCERT__","all,compilers"],
["__COMPILER_VER__","all,compilers"],
["__convexc__","all,compilers"],
["__COVERITY__","all,compilers"],
["__CWCC__","all,compilers"],
["__CX51__","all,compilers"],
["__DCC__","all,compilers"],
["__DECC","all,compilers"],
["__DECC_VER","all,compilers"],
["__DECCXX","all,compilers"],
["__DECCXX_VER","all,compilers"],
["__DJGPP__","all,compilers"],
["__DJGPP_MINOR__","all,compilers"],
["__DMC__","all,compilers"],
["__ECC","all,compilers"],
["__EDG__","all,compilers"],
["__EDG_VERSION__","all,compilers"],
["__FCC_VERSION","all,compilers"],
["__ghs__","all,compilers"],
["__GHS_REVISION_DATE__","all,compilers"],
["__GHS_VERSION_NUMBER__","all,compilers"],
["__GNUC__","all,compilers"],
["__GNUC_MINOR__","all,compilers"],
["__GNUC_PATCHLEVEL__","all,compilers"],
["__GNUC_VERSION__","all,compilers"],
["__GO32__","all,compilers"],
["__HIGHC__","all,compilers"],
["__HITACHI__","all,compilers"],
["__HITACHI_VERSION__","all,compilers"],
["__HP_aCC","all,compilers"],
["__HP_cc","all,compilers"],
["__IAR_SYSTEMS_ICC__","all,compilers"],
["__IBMC__","all,compilers"],
["__IBMCPP__","all,compilers"],
["__ibmxl__","all,compilers"],
["__ibmxl_modification__","all,compilers"],
["__ibmxl_ptf_fix_level__","all,compilers"],
["__ibmxl_release__","all,compilers"],
["__ibmxl_version__","all,compilers"],
["__ibmxl_vrm__","all,compilers"],
["__ICC","all,compilers"],
["__ICL","all,compilers"],
["__IMAGECRAFT__","all,compilers"],
["__INTEL_COMPILER","all,compilers"],
["__INTEL_COMPILER_BUILD_DATE","all,compilers"],
["__KCC","all,compilers"],
["__KCC_VERSION","all,compilers"],
["__KEIL__","all,compilers"],
["__LCC__","all,compilers"],
["__llvm__","all,compilers"],
["__MINGW32__","all,compilers"],
["__MINGW32_MAJOR_VERSION","all,compilers"],
["__MINGW32_MINOR_VERSION","all,compilers"],
["__MINGW64__","all,compilers"],
["__MINGW64_VERSION_MAJOR","all,compilers"],
["__MINGW64_VERSION_MINOR","all,compilers"],
["__MRC__","all,compilers"],
["__MVS__","all,compilers"],
["__MWERKS__","all,compilers"],
["__NDPC__","all,compilers"],
["__NDPX__","all,compilers"],
["__NWCC__","all,compilers"],
["__OPEN64__","all,compilers"],
["__OPENCC__","all,compilers"],
["__OPENCC_MINOR__","all,compilers"],
["__OPENCC_PATCHLEVEL__","all,compilers"],
["__PACIFIC__","all,compilers"],
["__PATHCC__","all,compilers"],
["__PATHCC_MINOR__","all,compilers"],
["__PATHCC_PATCHLEVEL__","all,compilers"],
["__PGI","all,compilers"],
["__PGIC__","all,compilers"],
["__PGIC_MINOR__","all,compilers"],
["__PGIC_PATCHLEVEL__","all,compilers"],
["__POCC__","all,compilers"],
["__RENESAS__","all,compilers"],
["__RENESAS_VERSION__","all,compilers"],
["__REVISION__","all,compilers"],
["__SASC","all,compilers"],
["__SASC__","all,compilers"],
["__SC__","all,compilers"],
["__SCO_VERSION__","all,compilers"],
["__sgi","all,compilers"],
["__SNC__","all,compilers"],
["__SUNPRO_C","all,compilers"],
["__SUNPRO_CC","all,compilers"],
["__SYSC__","all,compilers"],
["__SYSC_VER__","all,compilers"],
["__TenDRA__","all,compilers"],
["__TI_COMPILER_VERSION__","all,compilers"],
["__TINYC__","all,compilers"],
["__TURBOC__","all,compilers"],
["__USLC__","all,compilers"],
["__VAXC","all,compilers"],
["__VBCC__","all,compilers"],
["__VER__","all,compilers"],
["__VERSION","all,compilers"],
["__VERSION__","all,compilers"],
["__VERSION_NUMBER__","all,compilers"],
["__VOSC__","all,compilers"],
["__WATCOMC__","all,compilers"],
["__xlC__","all,compilers"],
["__xlc__","all,compilers"],
["__xlC_ver__","all,compilers"],
["__ZTC__","all,compilers"],
["_ACC_","all,compilers"],
["_COMPILER_VERSION","all,compilers"],
["_CRAYC","all,compilers"],
["_DICE","all,compilers"],
["_MAJOR_REV","all,compilers"],
["_MINOR_REV","all,compilers"],
["_MRI","all,compilers"],
["_MSC_BUILD","all,compilers"],
["_MSC_FULL_VER","all,compilers"],
["_MSC_VER","all,compilers"],
["_PACC_VER","all,compilers"],
["_RELEASE","all,compilers"],
["_RELEASE_MINOR","all,compilers"],
["_SCO_DS","all,compilers"],
["_SGI_COMPILER_VERSION","all,compilers"],
["_TMS320C6X","all,compilers"],
["_UCC","all,compilers"],
["AZTEC_C","all,compilers"],
["MIRACLE","all,compilers"],
["MPW_C","all,compilers"],
["MPW_CPLUS","all,compilers"],
["ORA_PROC","all,compilers"],
["SASC","all,compilers"],
["SDCC","all,compilers"],
["sgi","all,compilers"],
["THINKC3","all,compilers"],
["THINKC4","all,compilers"],
["VAXC","all,compilers"],


#https://sourceforge.net/p/predef/wiki/Architectures/
["__370__","all,arch"],
["__386","all,arch"],
["__386__","all,arch"],
["__aarch64__","all,arch"],
["__alpha","all,arch"],
["__alpha__","all,arch"],
["__alpha_ev4__","all,arch"],
["__alpha_ev5__","all,arch"],
["__alpha_ev6__","all,arch"],
["__amd64","all,arch"],
["__amd64__","all,arch"],
["__arm","all,arch"],
["__arm__","all,arch"],
["__ARM_ARCH_2__","all,arch"],
["__ARM_ARCH_3__","all,arch"],
["__ARM_ARCH_3M__","all,arch"],
["__ARM_ARCH_4T__","all,arch"],
["__ARM_ARCH_5__","all,arch"],
["__ARM_ARCH_5E__","all,arch"],
["__ARM_ARCH_5T__","all,arch"],
["__ARM_ARCH_5TE__","all,arch"],
["__ARM_ARCH_5TEJ__","all,arch"],
["__ARM_ARCH_6__","all,arch"],
["__ARM_ARCH_6J__","all,arch"],
["__ARM_ARCH_6K__","all,arch"],
["__ARM_ARCH_6T2__","all,arch"],
["__ARM_ARCH_6Z__","all,arch"],
["__ARM_ARCH_6ZK__","all,arch"],
["__ARM_ARCH_7__","all,arch"],
["__ARM_ARCH_7A__","all,arch"],
["__ARM_ARCH_7M__","all,arch"],
["__ARM_ARCH_7R__","all,arch"],
["__ARM_ARCH_7S__","all,arch"],
["__bfin","all,arch"],
["__BFIN__","all,arch"],
["__convex__","all,arch"],
["__convex_c1__","all,arch"],
["__convex_c2__","all,arch"],
["__convex_c32__","all,arch"],
["__convex_c34__","all,arch"],
["__convex_c38__","all,arch"],
["__epiphany__","all,arch"],
["__hppa","all,arch"],
["__HPPA11__","all,arch"],
["__HPPA20__","all,arch"],
["__hppa__","all,arch"],
["__HPPA__","all,arch"],
["__i386","all,arch"],
["__i386__","all,arch"],
["__i486__","all,arch"],
["__i586__","all,arch"],
["__i686__","all,arch"],
["__I86__","all,arch"],
["__IA32__","all,arch"],
["__ia64","all,arch"],
["__IA64__","all,arch"],
["__ia64__","all,arch"],
["__INTEL__","all,arch"],
["__itanium__","all,arch"],
["__m68k__","all,arch"],
["__MC68000__","all,arch"],
["__mc68000__","all,arch"],
["__mc68010__","all,arch"],
["__MC68020__","all,arch"],
["__mc68020__","all,arch"],
["__MC68030__","all,arch"],
["__mc68030__","all,arch"],
["__mc68040__","all,arch"],
["__mc68060__","all,arch"],
["__MC68K__","all,arch"],
["__mips","all,arch"],
["__MIPS__","all,arch"],
["__mips__","all,arch"],
["__MIPS_ISA2__","all,arch"],
["__MIPS_ISA3__","all,arch"],
["__MIPS_ISA4__","all,arch"],
["__PA7100__","all,arch"],
["__PA8000__","all,arch"],
["__powerpc","all,arch"],
["__powerpc64__","all,arch"],
["__powerpc__","all,arch"],
["__POWERPC__","all,arch"],
["__ppc","all,arch"],
["__ppc601__","all,arch"],
["__ppc603__","all,arch"],
["__ppc604__","all,arch"],
["__ppc64__","all,arch"],
["__PPC64__","all,arch"],
["__ppc__","all,arch"],
["__PPC__","all,arch"],
["__PPCBROADWAY__","all,arch"],
["__PPCGECKO__","all,arch"],
["__RISC2_0__","all,arch"],
["__s390__","all,arch"],
["__s390x__","all,arch"],
["__sh1__","all,arch"],
["__sh2__","all,arch"],
["__sh3__","all,arch"],
["__SH3__","all,arch"],
["__SH4__","all,arch"],
["__SH5__","all,arch"],
["__sh__","all,arch"],
["__sparc","all,arch"],
["__sparc__","all,arch"],
["__sparc_v8__","all,arch"],
["__sparc_v9__","all,arch"],
["__sparcv8","all,arch"],
["__sparcv9","all,arch"],
["__SYSC_ZARCH__","all,arch"],
["__TARGET_ARCH_ARM","all,arch"],
["__TARGET_ARCH_THUMB","all,arch"],
["__TARGET_ARM_4T","all,arch"],
["__thumb__","all,arch"],
["__THW_370__","all,arch"],
["__THW_INTEL__","all,arch"],
["__THW_RS6000","all,arch"],
["__TMS320C2000__","all,arch"],
["__TMS320C55X__","all,arch"],
["__TMS320C6X__","all,arch"],
["__TMS470__","all,arch"],
["__VOS__","all,arch"],
["__x86_64","all,arch"],
["__x86_64__","all,arch"],
["__X86__","all,arch"],
["__zarch__","all,arch"],
["_ARCH_440","all,arch"],
["_ARCH_450","all,arch"],
["_ARCH_601","all,arch"],
["_ARCH_603","all,arch"],
["_ARCH_604","all,arch"],
["_ARCH_PPC","all,arch"],
["_ARCH_PPC64","all,arch"],
["_ARCH_PWR","all,arch"],
["_ARCH_PWR2","all,arch"],
["_ARCH_PWR3","all,arch"],
["_ARCH_PWR4","all,arch"],
["_ARM","all,arch"],
["_IA64","all,arch"],
["_IBMR2","all,arch"],
["_M_ALPHA","all,arch"],
["_M_AMD64","all,arch"],
["_M_ARM","all,arch"],
["_M_ARMT","all,arch"],
["_M_I386","all,arch"],
["_M_I86","all,arch"],
["_M_IA64","all,arch"],
["_M_IX86","all,arch"],
["_M_PPC","all,arch"],
["_MIPS_ISA","all,arch"],
["_MIPS_ISA_MIPS1","all,arch"],
["_MIPS_ISA_MIPS2","all,arch"],
["_MIPS_ISA_MIPS3","all,arch"],
["_MIPS_ISA_MIPS4","all,arch"],
["_PA_RISC1_0","all,arch"],
["_PA_RISC1_1","all,arch"],
["_PA_RISC2_0","all,arch"],
["_POWER","all,arch"],
["_R3000","all,arch"],
["_R4000","all,arch"],
["_R5900","all,arch"],
["_TMS320C28X","all,arch"],
["_TMS320C2XX","all,arch"],
["_TMS320C5X","all,arch"],
["_TMS320C5XX","all,arch"],
["_TMS320C6200","all,arch"],
["_TMS320C6400","all,arch"],
["_TMS320C6400_PLUS","all,arch"],
["_TMS320C6600","all,arch"],
["_TMS320C6700","all,arch"],
["_TMS320C6700_PLUS","all,arch"],
["_TMS320C6740","all,arch"],
["_TMS320C6X","all,arch"],
["_X86_","all,arch"],
["_XENON","all,arch"],
["i386","all,arch"],
["M68000","all,arch"],
["mips","all,arch"],
["pyr","all,arch"],

#https://sourceforge.net/p/predef/wiki/OperatingSystems/
["__amigaos__","all,os"],
["__ANDROID__","all,os"],
["__ANDROID_API__","all,os"],
["__APPLE__","all,os"],
["__BEOS__","all,os"],
["__bg__","all,os"],
["__bgq__","all,os"],
["__bsdi__","all,os"],
["__convex__","all,os"],
["__crayx1","all,os"],
["__CYGWIN__","all,os"],
["__DGUX__","all,os"],
["__dgux__","all,os"],
["__DOS__","all,os"],
["__DragonFly__","all,os"],
["__ECOS","all,os"],
["__EMX__","all,os"],
["__FreeBSD__","all,os"],
["__FreeBSD_kernel__","all,os"],
["__FreeBSD_version","all,os"],
["__GLIBC__","all,os"],
["__GNU__","all,os"],
["__gnu_hurd__","all,os"],
["__gnu_linux__","all,os"],
["__hiuxmpp","all,os"],
["__HOS_MVS__","all,os"],
["__hpux","all,os"],
["__INTEGRITY","all,os"],
["__INTERIX","all,os"],
["__linux","all,os"],
["__linux__","all,os"],
["__Lynx__","all,os"],
["__MACH__","all,os"],
["__minix","all,os"],
["__MORPHOS__","all,os"],
["__mpexl","all,os"],
["__MSDOS__","all,os"],
["__MVS__","all,os"],
["__NetBSD__","all,os"],
["__NetBSD_Version__","all,os"],
["__nucleus__","all,os"],
["__OpenBSD__","all,os"],
["__OS2__","all,os"],
["__OS400__","all,os"],
["__OS400_TGTVRM__","all,os"],
["__OS9000","all,os"],
["__osf","all,os"],
["__osf__","all,os"],
["__palmos__","all,os"],
["__QNX__","all,os"],
["__QNXNTO__","all,os"],
["__RTP__","all,os"],
["__sgi","all,os"],
["__sun","all,os"],
["__SunOS_5_7","all,os"],
["__SunOS_5_8","all,os"],
["__SVR4","all,os"],
["__svr4__","all,os"],
["__SYLLABLE__","all,os"],
["__SYMBIAN32__","all,os"],
["__sysv__","all,os"],
["__TANDEM","all,os"],
["__THW_BLUEGENE__","all,os"],
["__TOS_AIX__","all,os"],
["__TOS_BGQ__","all,os"],
["__TOS_MVS__","all,os"],
["__TOS_OS2__","all,os"],
["__TOS_WIN__","all,os"],
["__ultrix","all,os"],
["__ultrix__","all,os"],
["__unix","all,os"],
["__unix__","all,os"],
["__VMS","all,os"],
["__VMS_VER","all,os"],
["__VOS__","all,os"],
["__vxworks","all,os"],
["__VXWORKS__","all,os"],
["__WIN32__","all,os"],
["__WINDOWS__","all,os"],
["_AIX","all,os"],
["_AIX3","all,os"],
["_AIX32","all,os"],
["_AIX41","all,os"],
["_AIX43","all,os"],
["_CRAY","all,os"],
["_hpux","all,os"],
["_MSDOS","all,os"],
["_NTO_VERSION","all,os"],
["_OS2","all,os"],
["_OSK","all,os"],
["_SCO_DS","all,os"],
["_SEQUENT_","all,os"],
["_SYSTYPE_BSD","all,os"],
["_SYSTYPE_SVR4","all,os"],
["_UNICOS","all,os"],
["_UNIXWARE7","all,os"],
["_UWIN","all,os"],
["_WIN16","all,os"],
["_WIN32","all,os"],
["_WIN32_WCE","all,os"],
["_WIN64","all,os"],
["_WINDU_SOURCE","all,os"],
["_WRS_KERNEL","all,os"],
["_WRS_VXWORKS_MAINT","all,os"],
["_WRS_VXWORKS_MAJOR","all,os"],
["_WRS_VXWORKS_MINOR","all,os"],
["aegis","all,os"],
["AMIGA","all,os"],
["apollo","all,os"],
["BBNDK_VERSION_CURRENT","all,os"],
["BSD","all,os"],
["BSD4_2","all,os"],
["BSD4_3","all,os"],
["BSD4_4","all,os"],
["DGUX","all,os"],
["EPLAN9","all,os"],
["hpux","all,os"],
["linux","all,os"],
["M_I386","all,os"],
["M_XENIX","all,os"],
["macintosh","all,os"],
["Macintosh","all,os"],
["mpeix","all,os"],
["MSDOS","all,os"],
["NetBSD0_8","all,os"],
["NetBSD0_9","all,os"],
["NetBSD1_0","all,os"],
["OpenBSD3_1","all,os"],
["OpenBSD3_9","all,os"],
["OS2","all,os"],
["pyr","all,os"],
["sco","all,os"],
["sequent","all,os"],
["sgi","all,os"],
["sinux","all,os"],
["sun","all,os"],
["ultrix","all,os"],
["unix","all,os"],
["UTS","all,os"],
["vax","all,os"],
["VMS","all,os"],
["WIN32_PLATFORM_HPC2000","all,os"],
["WIN32_PLATFORM_HPCPRO","all,os"],
["WIN32_PLATFORM_PSPC","all,os"],
["WIN32_PLATFORM_WFSP","all,os"],

#https://developer.arm.com/documentation/dui0774/g/chr1383660321827
["__aarch64__", "all,arm"],
["__APCS_ROPI", "all,arm"],
["__APCS_RWPI", "all,arm"],
["__ARM_64BIT_STATE", "all,arm"],
["__arm__", "all,arm"],
["__ARM_ALIGN_MAX_STACK_PWR", "all,arm"],
["__ARM_ARCH", "all,arm"],
["__ARM_ARCH_EXT_IDIV__", "all,arm"],
["__ARM_ARCH_ISA_A64", "all,arm"],
["__ARM_ARCH_PROFILE", "all,arm"],
["__ARM_BIG_ENDIAN", "all,arm"],
["__ARM_FEATURE_CLZ", "all,arm"],
["__ARM_FEATURE_CMSE", "all,arm"],
["__ARM_FEATURE_CRC32", "all,arm"],
["__ARM_FEATURE_CRYPTO", "all,arm"],
["__ARM_FEATURE_DIRECTED_ROUNDING", "all,arm"],
["__ARM_FEATURE_DSP", "all,arm"],
["__ARM_FEATURE_FMA", "all,arm"],
["__ARM_FEATURE_IDIV", "all,arm"],
["__ARM_FEATURE_NUMERIC_MAXMIN", "all,arm"],
["__ARM_FEATURE_QBIT", "all,arm"],
["__ARM_FEATURE_SAT", "all,arm"],
["__ARM_FEATURE_SIMD32", "all,arm"],
["__ARM_FEATURE_UNALIGNED", "all,arm"],
["__ARM_FP", "all,arm"],
["__ARM_FP_FAST", "all,arm"],
["__ARM_NEON", "all,arm"],
["__ARM_NEON_FP", "all,arm"],
["__ARM_PCS", "all,arm"],
["__ARM_PCS_VFP", "all,arm"],
["__ARM_SIZEOF_MINIMAL_ENUM", "all,arm"],
["__ARM_SIZEOF_WCHAR_T", "all,arm"],
["__ARMCC_VERSION", "all,arm"],
["__ARMCOMPILER_VERSION", "all,arm"],
["__CHAR_UNSIGNED__", "all,arm"],
["__cplusplus", "all,arm"],
["__EXCEPTIONS", "all,arm"],
["__GNUC__", "all,arm"],
["__GNUC_MINOR__", "all,arm"],
["__INTMAX_TYPE__", "all,arm"],
["__NO_INLINE__", "all,arm"],
["__OPTIMIZE__", "all,arm"],
["__OPTIMIZE_SIZE__", "all,arm"],
["__PTRDIFF_TYPE__", "all,arm"],
["__SIZE_TYPE__", "all,arm"],
["__SOFTFP__", "all,arm"],
["__STDC__", "all,arm"],
["__STRICT_ANSI__", "all,arm"],
["__thumb__", "all,arm"],
["__UINTMAX_TYPE__", "all,arm"],
["__VERSION__", "all,arm"],
["__WCHAR_TYPE__", "all,arm"],
["__WINT_TYPE__", "all,arm"],

]


def filter():
	filtered_values = {}
	for e in sources:
		key = e[0]
		tags = [t.strip() for t in e[1].split(",")]
		kt = filtered_values.setdefault(key,set())
		for t in tags:
			kt.add(t)

	return filtered_values

def write_entry(file, key, tags):
	
	file.write('#ifdef ' + key + '\n')
	file.write('\tKEY("' + key + '");\n');
	if "typedef" in tags:
		file.write('\tTYPEDEF(' + key + ');\n');
	elif not "novalue" in tags:
		file.write('\tVALUE(' + key + ');\n');
	file.write('\tTAGS("' + ','.join(tags) + '");\n');
	file.write('#endif\n')


data = filter()
f = open(os.path.join(_this_dir,"src","autogenerated_defines.h"),"w")
for k,v in data.items():
	write_entry(f,k,v)
f.close()
